# Generated by Django 6.0.4 on 2026-05-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_current_level'),
        ('curriculum', '0002_seed_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField(help_text='The question, in markdown or plain text.')),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice (one answer)'), ('multi_select', 'Multiple choice (multiple answers)'), ('true_false', 'True / false'), ('short_answer', 'Short answer (manual grade)')], max_length=14)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Shown after submission. Helps the student learn from mistakes.')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=400)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'verbose_name': 'choice',
                'verbose_name_plural': 'choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lesson_quiz', 'Lesson quiz'), ('course_final', 'Course final'), ('placement', 'Placement test')], max_length=14)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, help_text='Percentage required to pass (0–100).')),
                ('randomize_questions', models.BooleanField(default=False, help_text='Shuffle question order for each attempt.')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Optional time limit. Blank = no limit.', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Set for course_final; leave blank otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='curriculum.course')),
                ('lesson', models.ForeignKey(blank=True, help_text='Set for lesson_quiz; leave blank otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted (awaiting grade)'), ('graded', 'Graded')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Percentage 0–100, computed by the grader.', null=True)),
                ('passed', models.BooleanField(blank=True, help_text='Denormalised: score >= quiz.pass_threshold.', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assessments.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='assessments.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.submission')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['submission', 'question__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='choice_unique_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='question_unique_order_per_quiz'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='answer_unique_submission_question'),
        ),
    ]
