# Generated by Django 6.0.4 on 2026-05-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_level',
            field=models.ForeignKey(blank=True, help_text='Cached current proficiency. Updated by placement / certificates / admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_at_level', to='curriculum.level'),
        ),
    ]
