# Generated by Django 6.0.4 on 2026-05-10 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_current_level'),
        ('curriculum', '0004_lesson_video_file_alter_lesson_primary_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished decks are hidden from students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'flashcard deck',
                'verbose_name_plural': 'flashcard decks',
                'ordering': ['lesson', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('front', models.CharField(help_text='Front side, typically the Arabic word or phrase.', max_length=400)),
                ('back', models.CharField(help_text='Back side, typically the English translation.', max_length=400)),
                ('front_lang', models.CharField(default='ar', help_text="ISO 639-1 (e.g. 'ar', 'en'). Drives template lang= for correct font + shaping.", max_length=8)),
                ('back_lang', models.CharField(default='en', max_length=8)),
                ('audio', models.FileField(blank=True, help_text='Optional audio file pronouncing the front-side word.', null=True, upload_to='flashcard_audio/')),
                ('notes', models.TextField(blank=True, help_text='Optional usage hints, example sentences, or grammar tips.')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.flashcarddeck')),
            ],
            options={
                'verbose_name': 'flashcard',
                'verbose_name_plural': 'flashcards',
                'ordering': ['deck', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveSmallIntegerField(default=0, help_text='Current correct-in-a-row count. Resets on miss.')),
                ('is_mastered', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_correct_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcards.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'flashcard review',
                'verbose_name_plural': 'flashcard reviews',
                'ordering': ['student', 'flashcard'],
            },
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('deck', 'order'), name='flashcard_unique_order_per_deck'),
        ),
        migrations.AddConstraint(
            model_name='flashcardreview',
            constraint=models.UniqueConstraint(fields=('student', 'flashcard'), name='review_unique_student_card'),
        ),
    ]
