# Generated by Django 6.0.4 on 2026-05-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_lesson_video_file_alter_lesson_primary_video_url'),
        ('games', '0002_seed_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='is_true',
            field=models.BooleanField(blank=True, help_text='Correct answer for True-or-False questions', null=True),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='word_tokens',
            field=models.JSONField(blank=True, default=list, help_text='Word tiles in display order, e.g. ["أنا","أذهب","إلى","المدرسة"]'),
        ),
        migrations.AlterField(
            model_name='vocabword',
            name='level',
            field=models.ForeignKey(blank=True, help_text='CEFR level this word belongs to (leave blank = all levels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab_words', to='curriculum.level'),
        ),
        migrations.AlterField(
            model_name='vocabword',
            name='missing_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-based index of the missing letter in the `letters` array', null=True),
        ),
        migrations.AlterField(
            model_name='vocabword',
            name='wrong_choices',
            field=models.JSONField(blank=True, default=list, help_text='2 wrong letter choices, e.g. ["ن","م"]'),
        ),
    ]
