# Generated by Django 6.0.4 on 2026-05-01 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'grammar', 'listening'.", max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Optional Bootstrap Icon name, e.g. 'book', 'mic-fill'.", max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text='Hide a category from the public catalogue without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. A1, A2, B1, B2, C1, C2', max_length=4, unique=True)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Beginner 1'", max_length=80)),
                ('order', models.PositiveSmallIntegerField(help_text='Sorting + prerequisite check. A1=1, A2=2, ..., C2=6.', unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('track', models.CharField(choices=[('all', 'All ages'), ('kids', 'Kids (under 12)'), ('teen', 'Teens (12–17)'), ('adult', 'Adults (18+)')], default='all', max_length=8)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished courses are hidden from the catalogue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.category')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, help_text='Leave empty for an open course (no level prerequisite).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.level')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='Set when the student finishes and a certificate is issued.')),
                ('course', models.ForeignKey(help_text='PROTECT — never delete a course that has enrolments.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='curriculum.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Display order within the course; 1 is first.')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('body_markdown', models.TextField(blank=True, help_text='Lesson body in markdown. Rendered by the lesson player.')),
                ('primary_video_url', models.URLField(blank=True, help_text='The main video for this lesson (YouTube/Vimeo embed URL).')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_free_preview', models.BooleanField(default=False, help_text='Free previews are viewable without enrolment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.course')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF'), ('docx', 'Word document'), ('pptx', 'Slide deck'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_attachments/')),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True, help_text='If False, students can view but not download.')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Auto-filled on save when an uploaded file is present.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'lesson attachment',
                'verbose_name_plural': 'lesson attachments',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='curriculum.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress',
                'ordering': ['enrollment', 'lesson__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='enrollment_unique_student_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='lesson_unique_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='lesson_unique_slug_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='lessonprogress_unique_enrollment_lesson'),
        ),
    ]
