# Generated by Django 6.0.4 on 2026-05-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_seed_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_code',
            field=models.CharField(blank=True, db_index=True, help_text='Stable token used as the URL slug for the public certificate page. Auto-set when the course is completed.', max_length=32),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='Optional override (e.g. PDF on S3). Usually empty; the on-site cert page is reachable via certificate_code.'),
        ),
    ]
