# Generated by Django 6.0.4 on 2026-05-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_enrollment_certificate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Self-hosted MP4 / WebM. Takes precedence over primary_video_url when set.', null=True, upload_to='lesson_videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='primary_video_url',
            field=models.URLField(blank=True, help_text='External video embed URL (YouTube /embed/<id> or player.vimeo.com/video/<id>). Used only when no video_file is uploaded.'),
        ),
    ]
